server:
  servlet:
    context-path: /recipe
  port: 9005

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: test
    username: test
    url: jdbc:h2:mem:cooking-instruction
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true